version: '3'

services:
  app:
    stdin_open: true
    build: .
    container_name: app
    depends_on:
      - db
    ports:
      - "3000:3000"
    expose:
      - 3000
    command: /bin/sh -c "npm run prisma:start && npm run db:server && npm run start"
    restart: always

  db:
    image: postgres
    container_name: database
    hostname: database
    ports:
      - 5432:5432
    expose:
      - 5432
    environment:
      POSTGRES_USER: postgres
      POSTGRES_PASSWORD: postgres
      POSTGRES_DB: database
    volumes:
      - postgres-data:/var/lib/postgresql/data
    restart: always

volumes:
  postgres-data: