version: '3'

services:
  users:
    stdin_open: true
    build: .
    container_name: users
    depends_on:
      - db
      - db-server
    ports:
      - "3001:3001"
    expose:
      - 3001
    command: /bin/sh -c "cd user && npm install && npm run prisma:start && npm run start"
    restart: always

  feeds:
    stdin_open: true
    build: .
    container_name: feeds
    depends_on:
      - db
      - db-server
      - users
    ports:
      - "3002:3002"
    expose:
      - 3002
    command: /bin/sh -c "cd feeds && npm install && npm run prisma:start &&  npm run start"
    restart: always

  detalhes:
    stdin_open: true
    build: .
    container_name: detalhes
    depends_on:
      - db
      - db-server
      - feeds
    ports:
      - "3003:3003"
    expose:
      - 3003
    command: /bin/sh -c "cd detalhes &&  npm install && npm run prisma:start && npm run start"
    restart: always

  db-server:
    stdin_open: true
    build: .
    container_name: db-server
    depends_on:
      - db
    ports:
      - "3004:3004"
    expose:
      - 3004
    command: /bin/sh -c "npm install && npm run prisma:start && npm run db:server"
    restart: on-failure

  db:
    image: postgres
    container_name: database
    hostname: database
    ports:
      - 5432:5432
    expose:
      - 5432
    environment:
      POSTGRES_USER: postgres
      POSTGRES_PASSWORD: postgres
      POSTGRES_DB: database
    volumes:
      - postgres-data:/var/lib/postgresql/data
    restart: always

volumes:
  postgres-data: